#---------------------------------------------------------INGRESOS SUELDO------------------------------------------------------------------------
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (1, 'Ingreso', '2018-01-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (2, 'Ingreso', '2018-02-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (3, 'Ingreso', '2018-03-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (4, 'Ingreso', '2018-04-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (5, 'Ingreso', '2018-05-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (6, 'Ingreso', '2018-06-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (7, 'Ingreso', '2018-07-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (8, 'Ingreso', '2018-08-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (9, 'Ingreso', '2018-09-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (10, 'Ingreso', '2018-10-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (11, 'Ingreso', '2018-11-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (12, 'Ingreso', '2018-12-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (13, 'Ingreso', '2019-01-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (14, 'Ingreso', '2019-02-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (15, 'Ingreso', '2019-03-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (16, 'Ingreso', '2019-04-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (17, 'Ingreso', '2019-05-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (18, 'Ingreso', '2019-06-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (19, 'Ingreso', '2019-07-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (20, 'Ingreso', '2019-08-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (21, 'Ingreso', '2019-09-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (22, 'Ingreso', '2019-10-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (23, 'Ingreso', '2019-11-05', 1200, 'Sueldo', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (24, 'Ingreso', '2019-12-05', 1200, 'Sueldo', 1);


#---------------------------------------------------------EGRESOS RENTA----------------------------------------------------------------------------------
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (25, 'Egreso', '2018-01-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (26, 'Egreso', '2018-02-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (27, 'Egreso', '2018-03-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (28, 'Egreso', '2018-04-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (29, 'Egreso', '2018-05-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (30, 'Egreso', '2018-06-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (31, 'Egreso', '2018-07-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (32, 'Egreso', '2018-08-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (33, 'Egreso', '2018-09-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (34, 'Egreso', '2018-10-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (35, 'Egreso', '2018-11-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (36, 'Egreso', '2018-12-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (37, 'Egreso', '2019-01-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (38, 'Egreso', '2019-02-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (39, 'Egreso', '2019-03-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (40, 'Egreso', '2019-04-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (41, 'Egreso', '2019-05-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (42, 'Egreso', '2019-06-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (43, 'Egreso', '2019-07-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (44, 'Egreso', '2019-08-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (45, 'Egreso', '2019-09-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (46, 'Egreso', '2019-10-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (47, 'Egreso', '2019-11-05', 500, 'Renta', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (48, 'Egreso', '2019-12-05', 500, 'Renta', 1);


#---------------------------------------------------------EGRESOS LUZ----------------------------------------------------------------------------------
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (49, 'Egreso', '2018-01-15', 25, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (50, 'Egreso', '2018-02-15', 27, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (51, 'Egreso', '2018-03-15', 20, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (52, 'Egreso', '2018-04-15', 28, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (53, 'Egreso', '2018-05-15', 28, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (54, 'Egreso', '2018-06-15', 28, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (55, 'Egreso', '2018-07-15', 25, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (56, 'Egreso', '2018-08-15', 26, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (57, 'Egreso', '2018-09-15', 22, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (58, 'Egreso', '2018-10-15', 20, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (59, 'Egreso', '2018-11-15', 22, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (60, 'Egreso', '2018-12-15', 25, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (61, 'Egreso', '2019-01-15', 27, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (62, 'Egreso', '2019-02-15', 29, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (63, 'Egreso', '2019-03-15', 32, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (64, 'Egreso', '2019-04-15', 20, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (65, 'Egreso', '2019-05-15', 21, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (66, 'Egreso', '2019-06-15', 24, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (67, 'Egreso', '2019-07-15', 26, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (68, 'Egreso', '2019-08-15', 30, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (69, 'Egreso', '2019-09-15', 28, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (70, 'Egreso', '2019-10-15', 22, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (71, 'Egreso', '2019-11-15', 21, 'Luz', 1);
INSERT INTO `mydb`.`Movimiento` (`idMovimiento`, `Tipo`, `Fecha`, `Monto`, `Concepto`, `idUsuario_FK`) VALUES (72, 'Egreso', '2019-12-15', 25, 'Luz', 1);